# The GTFS-RT feed base URL (no key appended here). You can override via environment variable or command line.
gtfsrt.feed.url=https://otd.delhi.gov.in/api/realtime/VehiclePositions.pb

# Add your key via environment variable or override below (not recommended to put private keys into source control)
gtfsrt.api.key=${GTFSRT_API_KEY:l20yfRg0FOToEYQULSBcceklVgxvLPQ1}

# Optional: polling interval if you later add polling (ms). We use on-demand fetch from controller.
gtfsrt.poll.ms=15000

# Server port (optional)
server.port=8080
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.url=jdbc:sqlite:./gtfs.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=none 
